language: swift
osx_image: xcode10
xcode_project: DiveLane.xcworkspace # path to your xcodeproj folder
xcode_scheme: DiveLane
xcode_destination: platform=iOS Simulator, OS=11.4, name=iPhone X
before_install:
  - brew update
  - brew install swiftlint
  - gem install cocoapods
  - pod install
script:
  - swiftlint
  - xcodebuild -workspace DiveLane.xcworkspace -scheme DiveLane -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace DiveLane.xcworkspace -scheme DiveLaneTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace DiveLane.xcworkspace -scheme DiveLaneUITests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
